version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html  # Copy to Apache root directory

hooks:
  AfterInstall:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root
