version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
  build:
    commands:
      - echo "Building the application"
      - mkdir -p artifacts
      - cp index.html artifacts/   # Copy index.html
      - cp appspec.yml artifacts/  # Copy appspec.yml
      - cp -r scripts artifacts/   # Copy scripts folder
      - cd artifacts
      - zip -r deployment-package.zip .  # Create ZIP file

artifacts:
  files:
    - artifacts/deployment-package.zip
  discard-paths: yes
